JWT-auth with CAS user provider
SiMDE-Projects/jeffrey-api pull request #2
Opened 2020-11-10 17:13 UTC by anto2oo

## Mise en place d'une authentication long-life depuis CAS avec JWT :

### Niveau CAS
Utilisation de l'API pour vérifier les credentials

### JWT
Utilisation du package [jwt-auth](https://github.com/tymondesigns/jwt-auth)

Au lieu d'utiliser 2 tokens (un access token et un refresh token), seul l'access token est utilisé.
Pour refresh l'access token, une requête vers `/auth/refresh` peut être effectuée (même avec un token expiré depuis un certain laps de temps, défini par `JWT_REFRESH_TTL`) afin d'obtenir un nouvel access token.
On pourra par exemple imaginer de refresh l'access token (qui sera valable par ex. 2h) à chaque démarrage de l'application.

2020-11-15 19:21 UTC, cesar-richard submitted a review, later dismissed

2020-11-15 19:21 UTC, cesar-richard commented on .env.example
> +# Validity of the renew token (users must re-login after that)
Donne l'unité :)

2020-11-15 19:21 UTC, cesar-richard commented on .env.example
> +JWT_SECRET=
Tu peux mettre une valeur d'exemple ici si tu veux genre "SuperSecretToken"

2020-11-16 17:11 UTC, anto2oo commented on .env.example
> +JWT_SECRET=
Enfait la valeur est générée automatiquement du coup je l'ai précisé dans un commentaire

2020-11-16 19:53 UTC, cesar-richard commented on .env.example
> +JWT_SECRET=
Mmm je suis pas chaud pour qu'elle soit générée aléatoirement au build d'hab mais pourquoi pas

2020-11-16 19:55 UTC, cesar-richard requested changes

2020-11-16 19:55 UTC, cesar-richard commented on bootstrap/app.php
> +// $app->middleware([]);
Bah euh enleve carrément la ligne nan ?

2020-11-16 19:56 UTC, cesar-richard submitted a review, later dismissed

2020-11-16 23:13 UTC, cesar-richard approved these changes

2020-11-16 23:15 UTC, merged